name = "reshare"
account_id = "22788d96116325ff531105e98c23bc95"
main = "src/worker.js"
compatibility_date = "2025-09-01"
workers_dev = true

[assets]
directory = "public"
binding = "ASSETS"
run_worker_first = true
html_handling = "none"
not_found_handling = "none"

[[kv_namespaces]]
binding = "RESUME_KV"
id = "904d3d264aa948f4ab88d61c60905e60"
